@echo off
echo [cool_pw_stealer] $ Collecting passwords...
echo [cool_pw_stealer] $ Collecting IP...
echo [cool_pw_stealer] $ Copying files...
echo [cool_pw_stealer] $ Encrypting files...
echo [cool_pw_stealer] $ Packaging the swag bag...
echo [cool_pw_stealer] $ Hippity hoppity, your personal info is my property!
